### PR TITLE
Updating documentation

### PR DESCRIPTION
**Pull request by bsieber-mozilla**
Multi-tasking during early calls. Had made some updates to the documentation to try and freshen it up a bit. 

Leaving this in draft, as it is not a priority and will come back to it at a later time (or do a different refresh down the line).

Just getting this off my local box.

### CODE REVIEW

**Review by jwhitlock — COMMENTED** [review]
This looks like a good set of changes. I think we could review and merge these, and return for another doc pass in a bit.

**Comment by bsieber-mozilla** [comment]
Going to refresh these a bit, rebase the branch, and submit as a pr

**Comment by bsieber-mozilla** [comment]
https://mozilla-it.github.io/ctms-api/

Updating the sphinx used here as well.

**Comment by bsieber-mozilla** [comment]
This is being merged into `main`, but it is required to merge to `gh-pages` for the docs to be formally rebuilt on https://mozilla-it.github.io/ctms-api/. 

_I believe we can change this behavior to be on `main` if desired._

**Review by cvalaas — APPROVED** [review]

**Pull request merged**
