### PR TITLE
Issue #47, if desired this PR addresses this issue

### PR DESCRIPTION
**Pull request by bsieber-mozilla**
## Proposed changes

Update TOML to align package to be named CTMS instead of ctms-api, which also has poetry to look at CTMS directory instead of using the packages section of the toml to determine where to look.

Not a necessary change, but just came up per the issue.

## Types of changes

What types of changes does your code introduce?
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [guides](https://github.com/mozilla-it/ctms-api/tree/main/guides)
- [x] I have followed the [Mozilla Lean Data Policies](https://www.mozilla.org/en-US/about/policy/lean-data/)
- [ ] Lint and tests pass both locally and on the cicd with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

_Use this space for additional comments, complications, learnings, alternatives,..._

### CODE REVIEW

**Review by jwhitlock — APPROVED** [review]
I've gotten a little more comfortable with this change as I work with installing new dependencies, approving.

I also think the "right" think to do is to install the project in the ``development`` build of the ``Dockerfile``, but that should be a different PR.

**Comment by bsieber-mozilla** [comment]
Yeah, I think @imbstack had run into an issue with the use of the `packages` section in the pyproj so it was removed [here](https://github.com/mozilla-it/ctms-api/commit/6c15930a10fbc6f118247ba83cae2e995d4a7fe1) and links to a poetry issue addressing the use of --no-root, when a `packages` section exists (it's a indexing issue it appears).

However, we can likely roll those, previously necessary changes of --no-root, back when we merge this PR in (or I can add it in here).

What are your thoughts @imbstack? Maybe there was another issue that popped up that I am unaware of that required the change, but I wouldn't want to slyly re-add something you were fighting. 

We can:

- [ ] drop this PR (it's not adding functionality, it's adhering to the poetry naming conventions of the package, w/o needing the packages section)
- [ ] add a commit to this PR addressing the --no-root
- [ ] add a followup PR with the --no-root

**Review by imbstack — APPROVED** [review]
awesome! feel free to address the `--no-root` thing in this PR or a followup. I agree this makes it unnecessary to have

**Comment by bsieber-mozilla** [comment]
I think this was the previous method that was called out, with the `--no-root` removal we have the poetry install and shell, able to use the internal packages, without `python` prefixed

Screen Shot 2021-03-08 at 2 41 07 PM

**Comment by bsieber-mozilla** [comment]
Merging this in; let me know of any concerns and we can rb

**Pull request merged**
