### PR TITLE
Basket Rotation Script/Process

### PR DESCRIPTION
**Pull request by bsieber-mozilla**
The current/prior basket processes of rotation current involved multiple coordinated parties, with data export/imports. 

https://docs.google.com/document/d/1T7vAHrUSTU0yiy3YcxDqh5pOJ2omNza6oX8ViGwy7AA/edit#

----

Intent of PR: 
- Simplify coordination
- Reduce data export necessity (PII)
- No downtime of API (although we could for better db perf)

Questions:
- Is this unacceptable?

### CODE REVIEW

**Comment by bsieber-mozilla** [comment]
I would love a basic review of this PR's intent. I think we might have most of the resources we need within CTMS--and not have to touch Acoustic (by using our background sync).

I pushed this commit with `no-verify` so theres some fixing for linters. 
(Also no tests currently)

**Comment by leplatrem** [comment]
What would be the overall strategy?

Questions that pop up in my head?
- How do you distinguish the contacts that were already rotated?
- Looking at the maximum rate of contacts per seconds handled by the background job, and the total number of contacts, what would be an optimistic estimation of the time required to rotate them all?
- How can we make sure this massive resync won't interfere with regular newsletters/waitlists (un)subscriptions?

**Comment by bsieber-mozilla** [comment]
> What would be the overall strategy?

The approach is to reduce PII data having to be exported, since we have the Acoustic sync job. 

1. (if required)  Similar to prior process -- Scale down/off service
2. Run script in CTMS
3. Observe metrics gauge and `failed_records` to determine records that requires retry.

Data exchange continue to happen through services, we can use the existing acoustic job. 

If we determine doing all email_ids at once is too costly, we could add some delay between loops--but that could mean all records to update takes a long time.

> Questions that pop up in my head?
> 
>     How do you distinguish the contacts that were already rotated?

We query for all contacts with non-null basket_tokens; then per-record log the success/failure and provide a metric gauge. The failed records are presented at the end of the script; success records could also be provided as output.

>     Looking at the maximum rate of contacts per seconds handled by the background job, and the total number of contacts, what would be an optimistic estimation of the time required to rotate them all?

Does this time estimation mean we are using all the DB resources and shut down the service, or we're ok with handling requests and having this job run over a few days possibly. 

>     How can we make sure this massive resync won't interfere with regular newsletters/waitlists (un)subscriptions?

We could do the same as what we did previously, shut down the service and call out the maintenance period.

---

What this script hopes to accomplish:
- reduce/remove PII on personal computers
- reduce/remove touches in DB (now scripted)
- use existing acoustic processing, instead of manual import job
- reduce coordination; limited SRE work request for script run, watch the gauge/logs

**Comment by bsieber-mozilla** [comment]
On March 7th, it shows that CTMS was able to handle a lot of traffic. This metric might be false: 

Contacts sync'd to acoustic per min: max 3,455,407 contacts/min
Screenshot 2023-04-19 at 9 25 56 AM

**Comment by bsieber-mozilla** [comment]
Looking into that last 40 days; a more reasonable max is 422.
8mil/422 = 18957.35 min = 316 hours = 13 days

**Comment by grahamalama** [comment]
For your estimates @bsieber-mozilla, where is the estimate of `8mil` coming from?

**Comment by bsieber-mozilla** [comment]
However, those times still seem to be unreasonable numbers; if we wanted to remove the schedule_acoustic_record call--this script can be converted to just the CTMS queries with split acoustic files as output. Or we use the  Acoustic SFTP apis?

**Comment by bsieber-mozilla** [comment]
I'm going to hold on this PR--and just inquire for SRE support-> this is the checklist I'll be following: 
https://docs.google.com/document/d/1b4-PCGzeIUQJADMB286W29J0Im8cz5Z25nNUv83Q1Kw/edit#heading=h.v73t256gwyb3

**Pull request closed without merging**
